### PR TITLE
taup: Remove taup_console

### PR DESCRIPTION
**Pull request by seisman**
taup_console is not available in TauP v2.4.5

### CODE REVIEW

**Comment by seisman** [comment]
@core-man Please note that I enabled auto-merge in settings:
image

The PR will be automatically merged if you approve. So don't approve it unless you have no suggestions.

**Comment by core-man** [comment]
I also enabled auto-merge for `seismology` and `seismology101`. How about other repos?

**Review by core-man — APPROVED** [review]

**Comment by seisman** [comment]
I think we can enable them all.

**Comment by seisman** [comment]
Actually, auto-merge may be a little unfriendly to reviewers. If the PR looks good but has a tiny typo, then you have to make the suggestions, but can't approve it (otherwise it will be automatically merged). After I accept your changes, you have to review it again and approve it.

**Comment by core-man** [comment]
I've enabled it for all the public repos. It does not work for private one.

> Actually, auto-merge may be a little unfriendly to reviewers. If the PR looks good but has a tiny typo, then you have to make the suggestions, but can't approve it (otherwise it will be automatically merged). After I accept your changes, you have to review it again and approve it.

We can use it and then decide if it is suitable for us.

**Comment by seisman** [comment]
> We can use it and then decide if it is suitable for us.

OK.

**Pull request merged**
