### PR TITLE
Update TauP install instructions

### PR DESCRIPTION
**Pull request by seisman**
**Description of proposed changes**

Address #182.

**PRs for new software/tutorials**

- [x] Software metadata is complete
- [x] The "last updated date" in the metadata page is up-to-date
- [x] All links work
- [x] You're listed as the author(s) in the metadata page
- [x] Anyone who have made significant contributions (e.g., review) to
      the tutorials are listed in the meteda page
- [ ] Add a test to weekly CI jobs

**PRs for bugs/improvements**

- [ ] You're listed as the proofreader in the metadata page

### CODE REVIEW

**Comment by seisman** [comment]
Please note that this PR will be merged into the taup-2.5.0 branch (i.e., #199).

**Comment by seisman** [comment]
Question: do you think we should add the Homebrew install instructions or not?

**Review by core-man — APPROVED** [review]

**Comment by core-man** [comment]
> Question: do you think we should add the Homebrew install instructions or not?

I am okay. We may choose to add a dropdown before step 1 to tell macOS users that they could use brew instead of step 2-5.

**Comment by seisman** [comment]
> > Question: do you think we should add the Homebrew install instructions or not?
> 
> I am okay. We may choose to add a dropdown before step 1 to tell macOS users that they could use brew instead of step 2-5.

I won't add the homebrew instructions now.

**Pull request merged**
