### PR TITLE
Install sphinx-cjkspace to remove extra whitespaces between CJK characters

### PR DESCRIPTION
**Pull request by core-man**
It seems that there will be a white space if an `enter` is used. Below is an example.

enter-2

enter-1

### CODE REVIEW

**Comment by seisman** [comment]
https://github.com/seisman/sphinx-cjkspace

We probably need this plugin.

**Comment by core-man** [comment]
Okay. I will install it.

**Comment by core-man** [comment]
> https://github.com/seisman/sphinx-cjkspace
> 
> We probably need this plugin.

Installed~

**Review by seisman — APPROVED** [review]

**Comment by seisman** [comment]
I believe we need to make the same changes in the other two repositories.

**Pull request merged**
